### ISSUE TITLE
[Suggestion] Add Fuel for Keys

### ISSUE THREAD

**Issue by Silverrain2004** [Lothrazar/DimStacker#2]
Hi there it is a very nice mod :) is it possible to add fuel for use the key? as example... Obsidian for Netherkey , Endereyes for Endkey and so on. Just to having a possibility to add fuels, that would be very nice. Becouse even if i make a recipe very difficult... they just need that item one time.. and they can travel as long and so often they want.

**Comment by Lothrazar** [comment]
in 0.1.0 the keys are new standalone items instead of existing items, lots of changes recently, check it out and id love some more feedback

**Comment by Shadows-of-Fire** [comment]
It is likely the keys will be consumable in the next update

**Comment by Shadows-of-Fire** [comment]
1.0.0
